import Head from 'next/head'
import useCustomer from '../backend/db/hooks/useCustomer'
import Form from '../components/Form'
import Layout from '../components/Layout'

export default function Home() {
  const { customerState } = useCustomer()

  return (
    <div className={`
      flex justify-center items-center h-screen
      bg-gradient-to-b from-sky-100 via-slate-200 to-gray-200
    
    `}>
      <Head>
        <title>CRUD Next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout title='Customer'>
        <Form customer={customerState} />
      </Layout>
    </div>
  )
}
