import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='
      flex h-screen justify-center items-center 
      '>
        <h1 className="text-3xl font-bold">
          CRUD Next
        </h1>
      </div>
    </>
  )
}
