import Head from 'next/head'
import Layout from '../components/Layout'
import Table from '../components/Table'
import Customer from '../core/Customer'

export default function Home() {
  const customersList = [
    new Customer('John Doe', 34, '1'),
    new Customer('Mary Doe', 26, '2'),
    new Customer('Ted Doe', 12, '3'),
    new Customer('Steve Doe', 8, '4'),
    new Customer('Keven Doe', 2, '5')
  ]



  return (
    <div className={`
      flex justify-center items-center h-screen
      bg-gradient-to-b from-sky-100 via-slate-200 to-gray-200
    
    `}>
      <Head>
        <title>CRUD Next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout title='Customers'>
        <Table customers={customersList}/>
      </Layout>
    </div>
  )
}
